# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/xilinx_2020/MB_Peripheral_step_driver/MB_Peripheral_step_driver.srcs/sources_1/bd/design_Combine_step/ip/design_Combine_step_dlmb_v10_0/design_Combine_step_dlmb_v10_0.xci
# IP: The module: 'design_Combine_step_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_2020/MB_Peripheral_step_driver/MB_Peripheral_step_driver.srcs/sources_1/bd/design_Combine_step/ip/design_Combine_step_dlmb_v10_0/design_Combine_step_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Combine_step_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/xilinx_2020/MB_Peripheral_step_driver/MB_Peripheral_step_driver.srcs/sources_1/bd/design_Combine_step/ip/design_Combine_step_dlmb_v10_0/design_Combine_step_dlmb_v10_0.xci
# IP: The module: 'design_Combine_step_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_2020/MB_Peripheral_step_driver/MB_Peripheral_step_driver.srcs/sources_1/bd/design_Combine_step/ip/design_Combine_step_dlmb_v10_0/design_Combine_step_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_Combine_step_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
