# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xilinx_2020/MY_Basys-3-Master.xdc

# Block Designs: bd/design_Combine_step/design_Combine_step.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step || ORIG_REF_NAME==design_Combine_step} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_microblaze_0_0/design_Combine_step_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_microblaze_0_0 || ORIG_REF_NAME==design_Combine_step_microblaze_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_dlmb_v10_0/design_Combine_step_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_dlmb_v10_0 || ORIG_REF_NAME==design_Combine_step_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_ilmb_v10_0/design_Combine_step_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_ilmb_v10_0 || ORIG_REF_NAME==design_Combine_step_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_dlmb_bram_if_cntlr_0/design_Combine_step_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_Combine_step_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_ilmb_bram_if_cntlr_0/design_Combine_step_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_Combine_step_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_lmb_bram_0/design_Combine_step_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_lmb_bram_0 || ORIG_REF_NAME==design_Combine_step_lmb_bram_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_xbar_0/design_Combine_step_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_xbar_0 || ORIG_REF_NAME==design_Combine_step_xbar_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_microblaze_0_axi_periph_0/design_Combine_step_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_Combine_step_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_microblaze_0_axi_intc_0/design_Combine_step_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_Combine_step_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_microblaze_0_xlconcat_0/design_Combine_step_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_Combine_step_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_mdm_1_0/design_Combine_step_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_mdm_1_0 || ORIG_REF_NAME==design_Combine_step_mdm_1_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_clk_wiz_1_0/design_Combine_step_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_clk_wiz_1_0 || ORIG_REF_NAME==design_Combine_step_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_rst_clk_wiz_1_100M_0/design_Combine_step_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_Combine_step_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_gpio_0_0/design_Combine_step_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_gpio_0_0 || ORIG_REF_NAME==design_Combine_step_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_gpio_1_0/design_Combine_step_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_gpio_1_0 || ORIG_REF_NAME==design_Combine_step_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_gpio_2_0/design_Combine_step_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_gpio_2_0 || ORIG_REF_NAME==design_Combine_step_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_uartlite_0_0/design_Combine_step_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_uartlite_0_0 || ORIG_REF_NAME==design_Combine_step_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_timer_0_0/design_Combine_step_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_timer_0_0 || ORIG_REF_NAME==design_Combine_step_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_StepMotorController_0_0/design_Combine_step_StepMotorController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_StepMotorController_0_0 || ORIG_REF_NAME==design_Combine_step_StepMotorController_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_StepMotorController_1_0/design_Combine_step_StepMotorController_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_StepMotorController_1_0 || ORIG_REF_NAME==design_Combine_step_StepMotorController_1_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_StepMotorController_2_0/design_Combine_step_StepMotorController_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_StepMotorController_2_0 || ORIG_REF_NAME==design_Combine_step_StepMotorController_2_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_AXI4_tickGenerator_0_0/design_Combine_step_AXI4_tickGenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_AXI4_tickGenerator_0_0 || ORIG_REF_NAME==design_Combine_step_AXI4_tickGenerator_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_AXI4_BuzzerPWM_0_0/design_Combine_step_AXI4_BuzzerPWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_AXI4_BuzzerPWM_0_0 || ORIG_REF_NAME==design_Combine_step_AXI4_BuzzerPWM_0_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_axi_gpio_3_0/design_Combine_step_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_axi_gpio_3_0 || ORIG_REF_NAME==design_Combine_step_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_Combine_step/ip/design_Combine_step_AXI4_BCD_to_FND_0_0/design_Combine_step_AXI4_BCD_to_FND_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Combine_step_AXI4_BCD_to_FND_0_0 || ORIG_REF_NAME==design_Combine_step_AXI4_BCD_to_FND_0_0} -quiet] -quiet

# XDC: bd/design_Combine_step/design_Combine_step_ooc.xdc
