/*
 * Stepmotor.c
 *
 *  Created on: 2022. 11. 3.
 *      Author: kccistc
 */


#include "Stepmotor.h"

void StepMotor_Working(int mode)
{
	if(mode) //HALF
	{
		STEPMOTOR_SEC_FREQUENCY1_REGISTER = 17066;
		STEPMOTOR_SEC_FREQUENCY2_REGISTER = 125;
		STEPMOTOR_SEC_INPUTSTEP_REGISTER = 4096;

		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 2844;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 1250;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 4096;

		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 9482;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 12500;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 4096;
	}
	if(!mode) //Full
	{
		STEPMOTOR_SEC_FREQUENCY1_REGISTER = 34133;
		STEPMOTOR_SEC_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_SEC_INPUTSTEP_REGISTER = 2048;

		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 56889;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 25000;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 2048;

		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 4741;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 25000;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 2048;
	}
}

void StepMotor_Clear(int mode)
{
	if(mode)
	{
		STEPMOTOR_SEC_FREQUENCY1_REGISTER = 100000;
		STEPMOTOR_SEC_FREQUENCY2_REGISTER = 125;
		STEPMOTOR_SEC_INPUTSTEP_REGISTER = 4096;

		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 1000000;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 1250;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 4096;

		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 10000000;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 12500;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 4096;
	}
	if(!mode)
	{
		STEPMOTOR_SEC_FREQUENCY1_REGISTER = 100000;
		STEPMOTOR_SEC_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_SEC_INPUTSTEP_REGISTER = 2048;

		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 10000000;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 25000;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 2048;

		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 10000000;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 25000;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 2048;
	}
}

int motorDir = 0;

void StepMotor_Dir(int motorDir)
{
	if(motorDir)
	{
		STEPMOTOR_SEC_CONTROL_REGISTER &=  0xfb;
		STEPMOTOR_MIN_CONTROL_REGISTER &= 0xfb;
		STEPMOTOR_HOUR_CONTROL_REGISTER &= 0xfb;
	}
	else
	{
		STEPMOTOR_SEC_CONTROL_REGISTER |= 0x04;
		STEPMOTOR_MIN_CONTROL_REGISTER |= 0x04;
		STEPMOTOR_HOUR_CONTROL_REGISTER |= 0x04;
	}
}

void StepMotor_Mode(int motorMode)
{
	if(motorMode)
	{
		STEPMOTOR_SEC_CONTROL_REGISTER &= 0xfe;
		STEPMOTOR_MIN_CONTROL_REGISTER &= 0xfe;
		STEPMOTOR_HOUR_CONTROL_REGISTER &= 0xfe;
		STEPMOTOR_SEC_CONTROL_REGISTER |= 0x02;
		STEPMOTOR_MIN_CONTROL_REGISTER |= 0x02;
		STEPMOTOR_HOUR_CONTROL_REGISTER |= 0x02;
	}
	else
	{
		STEPMOTOR_SEC_CONTROL_REGISTER &=  0xfc;
		STEPMOTOR_MIN_CONTROL_REGISTER &= 0xfc;
		STEPMOTOR_HOUR_CONTROL_REGISTER &= 0xfc;
		STEPMOTOR_SEC_CONTROL_REGISTER |= 0x01;
		STEPMOTOR_MIN_CONTROL_REGISTER |= 0x01;
		STEPMOTOR_HOUR_CONTROL_REGISTER |= 0x01;
	}
}

void StepMotor_SEC_Stop()
{
	STEPMOTOR_SEC_FREQUENCY1_REGISTER = 0;
}

void StepMotor_MIN_Stop()
{
	STEPMOTOR_MIN_FREQUENCY1_REGISTER = 0;
}

void StepMotor_HOUR_Stop()
{
	STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 0;
}

void StepMotor_Min_Plus(int mode)
{
	if(mode)
	{
		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 68267;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 512;
		usleep(500000);
		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 0;
	}
	if(!mode)
	{
		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 34139;
		STEPMOTOR_MIN_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_MIN_INPUTSTEP_REGISTER = 512;
		usleep(500000);
		STEPMOTOR_MIN_FREQUENCY1_REGISTER = 0;
	}
}

void StepMotor_Hour_Plus(int mode)
{
	if(mode) // HALF
	{
		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 65536;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 512;
		usleep(2500000);
		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 0;
	}
	if(!mode) //FULL
	{
		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 34139;
		STEPMOTOR_HOUR_FREQUENCY2_REGISTER = 250;
		STEPMOTOR_HOUR_INPUTSTEP_REGISTER = 512;
		usleep(2500000);
		STEPMOTOR_HOUR_FREQUENCY1_REGISTER = 0;
	}
}
